//
// File generated by rootcint at Mon Mar 18 16:14:57 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME nanoDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "nanoDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void JNucleon_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JNucleon(void *p = 0);
   static void *newArray_JNucleon(Long_t size, void *p);
   static void delete_JNucleon(void *p);
   static void deleteArray_JNucleon(void *p);
   static void destruct_JNucleon(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::JNucleon*)
   {
      ::JNucleon *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JNucleon >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JNucleon", ::JNucleon::Class_Version(), "./JNucleon.h", 6,
                  typeid(::JNucleon), ::ROOT::DefineBehavior(ptr, ptr),
                  &::JNucleon::Dictionary, isa_proxy, 4,
                  sizeof(::JNucleon) );
      instance.SetNew(&new_JNucleon);
      instance.SetNewArray(&newArray_JNucleon);
      instance.SetDelete(&delete_JNucleon);
      instance.SetDeleteArray(&deleteArray_JNucleon);
      instance.SetDestructor(&destruct_JNucleon);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::JNucleon*)
   {
      return GenerateInitInstanceLocal((::JNucleon*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JNucleon*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr JNucleon::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *JNucleon::Class_Name()
{
   return "JNucleon";
}

//______________________________________________________________________________
const char *JNucleon::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::JNucleon*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int JNucleon::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::JNucleon*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void JNucleon::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::JNucleon*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *JNucleon::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::JNucleon*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void JNucleon::Streamer(TBuffer &R__b)
{
   // Stream an object of class JNucleon.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(JNucleon::Class(),this);
   } else {
      R__b.WriteClassBuffer(JNucleon::Class(),this);
   }
}

//______________________________________________________________________________
void JNucleon::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JNucleon.
      TClass *R__cl = ::JNucleon::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "r", &r);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "azimuthalAngle", &azimuthalAngle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "polarAngle", &polarAngle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bIsParticipant", &bIsParticipant);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_JNucleon(void *p) {
      return  p ? new(p) ::JNucleon : new ::JNucleon;
   }
   static void *newArray_JNucleon(Long_t nElements, void *p) {
      return p ? new(p) ::JNucleon[nElements] : new ::JNucleon[nElements];
   }
   // Wrapper around operator delete
   static void delete_JNucleon(void *p) {
      delete ((::JNucleon*)p);
   }
   static void deleteArray_JNucleon(void *p) {
      delete [] ((::JNucleon*)p);
   }
   static void destruct_JNucleon(void *p) {
      typedef ::JNucleon current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::JNucleon

/********************************************************
* nanoDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablenanoDict();

extern "C" void G__set_cpp_environmentnanoDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("JHistos.h");
  G__add_compiledheader("JNucleon.h");
  G__cpp_reset_tagtablenanoDict();
}
#include <new>
extern "C" int G__cpp_dllrevnanoDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JNucleon */
static int G__nanoDict_217_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JNucleon* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JNucleon[n];
     } else {
       p = new((void*) gvp) JNucleon[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JNucleon;
     } else {
       p = new((void*) gvp) JNucleon;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__nanoDictLN_JNucleon));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JNucleon* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new JNucleon(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
   } else {
     p = new((void*) gvp) JNucleon(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__nanoDictLN_JNucleon));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((JNucleon*) G__getstructoffset())->GetRadius());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((JNucleon*) G__getstructoffset())->GetAzimuthalAngle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((JNucleon*) G__getstructoffset())->GetPolarAngle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((JNucleon*) G__getstructoffset())->IsParticipant());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((JNucleon*) G__getstructoffset())->GetX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((JNucleon*) G__getstructoffset())->GetY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((JNucleon*) G__getstructoffset())->GetZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JNucleon*) G__getstructoffset())->SetRadius((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JNucleon*) G__getstructoffset())->SetAzimuthalAngle((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JNucleon*) G__getstructoffset())->SetPolarAngle((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JNucleon*) G__getstructoffset())->SetAsParticipant();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JNucleon*) G__getstructoffset())->SetCoordinatesFromCartesian((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JNucleon::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JNucleon::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JNucleon::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JNucleon::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JNucleon*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JNucleon::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JNucleon::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JNucleon::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__nanoDict_217_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JNucleon::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__nanoDict_217_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JNucleon* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JNucleon(*(JNucleon*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__nanoDictLN_JNucleon));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JNucleon G__TJNucleon;
static int G__nanoDict_217_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JNucleon*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JNucleon*) (soff+(sizeof(JNucleon)*i)))->~G__TJNucleon();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JNucleon*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JNucleon*) (soff))->~G__TJNucleon();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__nanoDict_217_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JNucleon* dest = (JNucleon*) G__getstructoffset();
   *dest = *(JNucleon*) libp->para[0].ref;
   const JNucleon& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JNucleon */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncnanoDict {
 public:
  G__Sizep2memfuncnanoDict(): p(&G__Sizep2memfuncnanoDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncnanoDict::*p)();
};

size_t G__get_sizep2memfuncnanoDict()
{
  G__Sizep2memfuncnanoDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancenanoDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__nanoDictLN_JNucleon))) {
     JNucleon *G__Lderived;
     G__Lderived=(JNucleon*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__nanoDictLN_JNucleon),G__get_linked_tagnum(&G__nanoDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablenanoDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__nanoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nanoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nanoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nanoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nanoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__nanoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__nanoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nanoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__nanoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__nanoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__nanoDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__nanoDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JNucleon */
static void G__setup_memvarJNucleon(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__nanoDictLN_JNucleon));
   { JNucleon *p; p=(JNucleon*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"r=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"azimuthalAngle=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"polarAngle=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"bIsParticipant=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__nanoDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarnanoDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJNucleon(void) {
   /* JNucleon */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__nanoDictLN_JNucleon));
   G__memfunc_setup("JNucleon",798,G__nanoDict_217_0_1, 105, G__get_linked_tagnum(&G__nanoDictLN_JNucleon), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JNucleon",798,G__nanoDict_217_0_2, 105, G__get_linked_tagnum(&G__nanoDictLN_JNucleon), -1, 0, 3, 1, 1, 0, 
"d - - 0 - - d - - 0 - - "
"d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRadius",904,G__nanoDict_217_0_3, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetAzimuthalAngle",1718,G__nanoDict_217_0_4, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPolarAngle",1285,G__nanoDict_217_0_5, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsParticipant",1339,G__nanoDict_217_0_6, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetX",376,G__nanoDict_217_0_7, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetY",377,G__nanoDict_217_0_8, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetZ",378,G__nanoDict_217_0_9, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetRadius",916,G__nanoDict_217_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - setR", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAzimuthalAngle",1730,G__nanoDict_217_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - setAzim", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPolarAngle",1297,G__nanoDict_217_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - setPolar", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetAsParticipant",1631,G__nanoDict_217_0_13, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetCoordinatesFromCartesian",2773,G__nanoDict_217_0_14, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - x d - - 0 - y "
"d - - 0 - z", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__nanoDict_217_0_15, 85, G__get_linked_tagnum(&G__nanoDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JNucleon::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__nanoDict_217_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JNucleon::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__nanoDict_217_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JNucleon::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__nanoDict_217_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JNucleon::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__nanoDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__nanoDict_217_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__nanoDict_217_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JNucleon::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__nanoDict_217_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JNucleon::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__nanoDict_217_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JNucleon::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__nanoDict_217_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JNucleon::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("JNucleon", 798, G__nanoDict_217_0_27, (int) ('i'), G__get_linked_tagnum(&G__nanoDictLN_JNucleon), -1, 0, 1, 1, 1, 0, "u 'JNucleon' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JNucleon", 924, G__nanoDict_217_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__nanoDict_217_0_29, (int) ('u'), G__get_linked_tagnum(&G__nanoDictLN_JNucleon), -1, 1, 1, 1, 1, 0, "u 'JNucleon' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncnanoDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalnanoDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcnanoDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__nanoDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__nanoDictLN_JNucleon = { "JNucleon" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablenanoDict() {
  G__nanoDictLN_TClass.tagnum = -1 ;
  G__nanoDictLN_TBuffer.tagnum = -1 ;
  G__nanoDictLN_TMemberInspector.tagnum = -1 ;
  G__nanoDictLN_TObject.tagnum = -1 ;
  G__nanoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__nanoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nanoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__nanoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__nanoDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__nanoDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__nanoDictLN_JNucleon.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablenanoDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__nanoDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__nanoDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__nanoDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__nanoDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__nanoDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__nanoDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nanoDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__nanoDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__nanoDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__nanoDictLN_TVectorTlEdoublegR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__nanoDictLN_JNucleon),sizeof(JNucleon),-1,324864,(char*)NULL,G__setup_memvarJNucleon,G__setup_memfuncJNucleon);
}
extern "C" void G__cpp_setupnanoDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupnanoDict()");
  G__set_cpp_environmentnanoDict();
  G__cpp_setup_tagtablenanoDict();

  G__cpp_setup_inheritancenanoDict();

  G__cpp_setup_typetablenanoDict();

  G__cpp_setup_memvarnanoDict();

  G__cpp_setup_memfuncnanoDict();
  G__cpp_setup_globalnanoDict();
  G__cpp_setup_funcnanoDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncnanoDict();
  return;
}
class G__cpp_setup_initnanoDict {
  public:
    G__cpp_setup_initnanoDict() { G__add_setup_func("nanoDict",(G__incsetup)(&G__cpp_setupnanoDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initnanoDict() { G__remove_setup_func("nanoDict"); }
};
G__cpp_setup_initnanoDict G__cpp_setup_initializernanoDict;

